project:
  type: book
  output-dir: docs

book:
  title: "Statistika dan Probabilitas"
  author: "Deri Siswara"
  page-footer: "Made with love and [Quarto](https://quarto.org/) by [Deri Siswara](https://derisiswara.art/) - [CC BY-SA 4.0](https://creativecommons.org/licenses/by-sa/4.0/)."
  chapters:
    - index.qmd
    - week1.qmd
    - week2.qmd
    - week3.qmd
    - week4.qmd
    - week5.qmd

format:
  html:
    theme: zephyr
    css: styles.css
    toc: true
    code-link: true
