on:
  workflow_dispatch:
  
name: "Render via Script"
jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      # for accessing this repo's assets in the container
      - name: Check out the repo
        uses: actions/checkout@v3
      # run the container, attaching this repo as a working directory
      - name: Run the build process with Docker
        uses: addnab/docker-run-action@v3
        with:
          image: stat20/stat20-docker:latest
          options: -v ${{ github.workspace }}:/home/rstudio/quarto-class-website
          shell: bash
          run: |
            # exit if any command returns non-zero exit
            set -e

            # execute from the textbook
            cd /home/rstudio/quarto-class-website/

            # render via script
            quarto run partial-render.ts
            
            # direct render
            # quarto render --profile partial-render
            